export const mockProducts = [
  {
    id: 1,
    name: "2025 Audi Q7",
    price: "65000",
    image: "/cars/audi_q7.avif",
    category: "SUV",
    location: "New York",
    description: "A luxury SUV with advanced features and a comfortable ride.",
    seller: "Auto Dealer",
  },
  {
    id: 2,
    name: "2025 Tesla Model S",
    price: "80000",
    image: "/cars/tesla-model-s.jpg",
    category: "Sedan",
    location: "Los Angeles",
    description: "An electric sedan with cutting-edge technology and performance.",
    seller: "Auto Dealer",
  },
  {
    id: 3,
    name: "2025 Ford F-150",
    price: "55000",
    image: "/cars/ford_f150.jpg",
    category: "Pickup",
    location: "Chicago",
    description: "A reliable and powerful pickup truck for all your needs.",
    seller: "Auto Dealer",
  },
  {
    id: 4,
    name: "2023 Toyota Corolla",
    price: "25000",
    image: "/cars/toyota_corolla.webp",
    category: "Sedan",
    location: "New York",
    description: "A compact sedan known for its reliability and fuel efficiency.",
    seller: "Auto Dealer",
  },
  {
    id: 5,
    name: "2024 BMW X5",
    price: "70000",
    image: "/cars/bmw_x5.webp",
    category: "SUV",
    location: "Los Angeles",
    description: "A luxury SUV with a sporty design and premium features.",
    seller: "Auto Dealer",
  },
  {
    id: 6,
    name: "2025 Chevrolet Silverado",
    price: "45000",
    image: "/cars/chevy_silverado.jpg",
    category: "Pickup",
    location: "Chicago",
    description: "A durable and versatile pickup truck for heavy-duty tasks.",
    seller: "Auto Dealer",
  },
  {
    id: 7,
    name: "2025 Toyota RAV4",
    category: "SUV",
    location: "New York",
    price: "28000",
    image: "/cars/toyota-rav4.jpg",
    description: "A compact SUV with great fuel efficiency and modern features.",
    seller: "Auto Dealer",
  },
  {
    id: 8,
    name: "2025 Honda Accord",
    category: "Sedan",
    location: "Los Angeles",
    price: "25000",
    image: "/cars/honda-accord.jpg",
    description: "A midsize sedan with a sleek design and advanced safety features.",
    seller: "Auto Dealer",
  },
  {
    id: 9,
    name: "2025 Chevrolet Tahoe",
    category: "SUV",
    location: "New York",
    price: "55000",
    image: "/cars/chevrolet-tahoe.jpg",
    description: "A full-size SUV with ample space and powerful performance.",
    seller: "Auto Dealer",
  },
];
