import { mockUsers } from "./mockUsers.js";

export const mockProducts = [
  {
    name: "2025 Audi Q7",
    description: "A luxury SUV with advanced features and a comfortable ride.",
    price: "9750000",
    category: "SUV",
    location: "Adama",
    imageUrl: "/cars/audi_q7.avif",
    seller: mockUsers[0]._id, // Reference to seller
    stock: 10,
    isFeatured: true,
  },
  {
    name: "2025 Tesla Model S",
    description: "An electric sedan with cutting-edge technology and performance.",
    price: "12000000",
    category: "Sedan",
    location: "Addis Ababa",
    imageUrl: "/cars/tesla-model-s.jpg",
    seller: mockUsers[0]._id,
    stock: 10,
    isFeatured: false,
  },
  {
    name: "2025 Ford F-150",
    description: "A reliable and powerful pickup truck for all your needs.",
    price: "8250000",
    category: "Pickup",
    location: "Dire Dawa",
    imageUrl: "/cars/ford_f150.jpg",
    seller: mockUsers[0]._id,
    stock: 10,
    isFeatured: true,
  },
  {
    name: "2023 Toyota Corolla",
    description: "A compact sedan known for its reliability and fuel efficiency.",
    price: "3750000",
    category: "Sedan",
    location: "Adama",
    imageUrl: "/cars/toyota_corolla.webp",
    seller: mockUsers[0]._id,
    stock: 10,
    isFeatured: false,
  },
  {
    name: "2024 BMW X5",
    description: "A luxury SUV with a sporty design and premium features.",
    price: "10500000",
    category: "SUV",
    location: "Addis Ababa",
    imageUrl: "/cars/bmw_x5.webp",
    seller: mockUsers[0]._id,
    stock: 10,
    isFeatured: true,
  },
  {
    name: "2025 Chevrolet Silverado",
    description: "A durable and versatile pickup truck for heavy-duty tasks.",
    price: "6750000",
    category: "Pickup",
    location: "Dire Dawa",
    imageUrl: "/cars/chevy_silverado.jpg",
    seller: mockUsers[0]._id,
    stock: 10,
    isFeatured: false,
  },
  {
    name: "2025 Toyota RAV4",
    description: "A compact SUV with great fuel efficiency and modern features.",
    price: "4200000",
    category: "SUV",
    location: "Adama",
    imageUrl: "/cars/toyota-rav4.jpg",
    seller: mockUsers[0]._id,
    stock: 10,
    isFeatured: true,
  },
  {
    name: "2025 Honda Accord",
    description: "A midsize sedan with a sleek design and advanced safety features.",
    price: "3750000",
    category: "Sedan",
    location: "Addis Ababa",
    imageUrl: "/cars/honda-accord.jpg",
    seller: mockUsers[0]._id,
    stock: 10,
    isFeatured: false,
  },
  {
    name: "2025 Chevrolet Tahoe",
    description: "A full-size SUV with ample space and powerful performance.",
    price: "8250000",
    category: "SUV",
    location: "Dire Dawa",
    imageUrl: "/cars/chevrolet-tahoe.jpg",
    seller: mockUsers[0]._id,
    stock: 10,
    isFeatured: false,
  },
  {
    name: 'Toyota Hilux',
    description: 'A reliable and powerful pickup truck perfect for all terrains.',
    price: '35000',
    category: 'Pickup',
    location: 'Addis Ababa',
    imageUrl: '/cars/hilux.jpg',
    seller: mockUsers[0]._id, // Reference to seller
    stock: 10,
    isFeatured: true,
  },
];
